import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'fs';
import { dirname, join, resolve } from 'path';

const ACE_GITIGNORE_BLOCK = [
  '# ACE local handoff artifacts',
  '.ace/',
].join('\n');

export function initProject({ workdir = null, force = false, codex = false } = {}) {
  const projectDir = resolve(workdir || process.cwd());
  const aceDir = join(projectDir, '.ace');
  const files = [];

  const aceDirExisted = existsSync(aceDir);
  mkdirSync(aceDir, { recursive: true });
  files.push({
    path: aceDir,
    role: 'state-directory',
    status: aceDirExisted ? 'exists' : 'created',
  });

  files.push(writeManagedFile({
    path: join(projectDir, 'ace.config.json'),
    role: 'project-config',
    content: defaultConfigText(),
    force,
  }));
  files.push(writeManagedFile({
    path: join(projectDir, 'AGENTS.md'),
    role: 'agent-instructions',
    content: agentInstructionsText(),
    force,
  }));
  files.push(ensureGitignoreIgnoresAce(projectDir));

  if (codex) {
    files.push(writeManagedFile({
      path: join(projectDir, '.codex', 'config.toml'),
      role: 'codex-mcp-config',
      content: codexConfigText(projectDir),
      force,
    }));
    files.push(writeManagedFile({
      path: join(projectDir, '.codex', 'hooks.json'),
      role: 'codex-hooks-config',
      content: codexHooksText(),
      force,
    }));
    files.push(writeManagedFile({
      path: join(projectDir, '.codex', 'hooks', 'ace-stop-handoff.cjs'),
      role: 'codex-stop-hook',
      content: codexStopHookText(),
      force,
    }));
  }

  return {
    schema: 'ace.init.v1',
    projectDir,
    files,
    nextSteps: [
      'Run ace start "current objective" before an AI coding task to open a new active task boundary.',
      'Have agents read ace experience --json before editing files.',
      'Run validations through ace run "command" so failures become durable evidence.',
      'Run ace brief --compact 8k before handing the task to another agent.',
      ...(codex ? [
        'Trust the generated .codex project config/hooks in Codex, then start a fresh desktop thread.',
        'Use ace_experience, ace_note, ace_run, and ace_brief through the ACE MCP server when available.',
      ] : []),
    ],
  };
}

export function formatInitSummary(result) {
  const lines = [];
  lines.push(`ACE initialized: ${result.projectDir}`);
  lines.push('Files:');
  for (const file of result.files) {
    lines.push(`  - ${file.status} ${file.path} (${file.role})`);
  }
  lines.push('Next steps:');
  for (const step of result.nextSteps) {
    lines.push(`  - ${step}`);
  }
  return lines.join('\n');
}

function writeManagedFile({ path, role, content, force }) {
  const existed = existsSync(path);
  if (existed && !force) {
    return {
      path,
      role,
      status: 'skipped-existing',
    };
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  return {
    path,
    role,
    status: existed ? 'overwritten' : 'created',
  };
}

function ensureGitignoreIgnoresAce(projectDir) {
  const path = join(projectDir, '.gitignore');
  const role = 'local-artifact-ignore';
  if (!existsSync(path)) {
    writeFileSync(path, `${ACE_GITIGNORE_BLOCK}\n`);
    return { path, role, status: 'created' };
  }

  const current = readFileSync(path, 'utf-8');
  if (/(^|\r?\n)\.ace\/?(\r?\n|$)/.test(current)) {
    return { path, role, status: 'exists' };
  }

  const separator = current.endsWith('\n') ? '' : '\n';
  writeFileSync(path, `${current}${separator}\n${ACE_GITIGNORE_BLOCK}\n`);
  return { path, role, status: 'updated' };
}

function codexConfigText(projectDir) {
  return `# ACE project-local Codex integration.
# Generated by ace init --codex.
# Codex loads this only after the project config is trusted.

[mcp_servers.ace]
command = "ace-mcp"
cwd = ${tomlString(toSlashPath(projectDir))}
startup_timeout_sec = 10
tool_timeout_sec = 60
default_tools_approval_mode = "prompt"

[mcp_servers.ace.tools.ace_experience]
approval_mode = "auto"

[mcp_servers.ace.tools.ace_status]
approval_mode = "auto"

[mcp_servers.ace.tools.ace_brief]
approval_mode = "auto"
`;
}

function codexHooksText() {
  return `${JSON.stringify({
    description: 'ACE project-local Codex hooks. Trust with /hooks before use.',
    hooks: {
      Stop: [
        {
          hooks: [
            {
              type: 'command',
              command: 'node .codex/hooks/ace-stop-handoff.cjs',
              timeout: 15,
              statusMessage: 'Writing ACE experience handoff',
            },
          ],
        },
      ],
    },
  }, null, 2)}\n`;
}

function codexStopHookText() {
  return `#!/usr/bin/env node
const { mkdirSync, writeFileSync } = require('fs');
const { join, resolve } = require('path');
const { spawnSync } = require('child_process');

const workdir = resolve(process.env.ACE_HOOK_WORKDIR || process.cwd());
const aceDir = join(workdir, '.ace');
const compact = process.env.ACE_HOOK_COMPACT || '8k';
const aceBin = process.env.ACE_BIN || 'ace';

function main() {
  mkdirSync(aceDir, { recursive: true });

  const experience = runAce([
    'experience',
    '--json',
    '--workdir',
    workdir,
  ]);
  if (experience.stdout) {
    writeFileSync(join(aceDir, 'codex-experience.json'), experience.stdout);
  }

  const brief = runAce([
    'brief',
    '--compact',
    compact,
    '--workdir',
    workdir,
  ]);

  writeFileSync(join(aceDir, 'codex-hook-status.json'), JSON.stringify({
    schema: 'ace.codex-hook-status.v1',
    generatedAt: new Date().toISOString(),
    ok: experience.exitCode === 0 && brief.exitCode === 0,
    commands: {
      experience: commandStatus(experience),
      brief: commandStatus(brief),
    },
  }, null, 2));

  if (experience.exitCode !== 0 || brief.exitCode !== 0) {
    process.stderr.write(
      experience.stderr
      || brief.stderr
      || experience.stdout
      || brief.stdout
      || 'ACE hook warning\\n',
    );
  }
}

function runAce(args) {
  const result = spawnSync(aceBin, args, {
    cwd: workdir,
    encoding: 'utf-8',
    shell: process.platform === 'win32',
    env: {
      ...process.env,
      CI: process.env.CI || '1',
    },
  });
  return {
    exitCode: result.status ?? 1,
    stdout: result.stdout || '',
    stderr: result.stderr || result.error?.message || '',
  };
}

function commandStatus(result) {
  return {
    exitCode: result.exitCode,
    stderr: result.stderr ? result.stderr.slice(0, 4000) : '',
    stdoutBytes: Buffer.byteLength(result.stdout || '', 'utf-8'),
  };
}

try {
  main();
} catch (error) {
  process.stderr.write(\`ACE hook warning: \${error.message}\\n\`);
}

// Hooks should not block Codex from stopping; failed evidence remains a warning.
process.exit(0);
`;
}

function defaultConfigText() {
  return `${JSON.stringify({
    ignore: [
      '.ace/**',
      'node_modules/**',
      'dist/**',
      'build/**',
      'coverage/**',
      '*.log',
    ],
    limits: {
      maxFiles: 120,
      maxDiffBytes: 60000,
      maxOutputBytes: 12000,
      maxPackBytes: 2000000,
      timeoutSeconds: 120,
    },
    preferredCommands: [
      {
        id: 'unit-tests',
        family: 'test',
        command: 'npm test',
        reason: 'Default test evidence for AI handoff.',
      },
    ],
    runPolicy: {
      allow: [],
      deny: [],
    },
    semantic: {
      enabled: false,
    },
    prompt: {
      profile: 'ai-coding-handoff',
      compactBudget: '8k',
      instructions: [
        'Treat ACE as the current engineering experience handoff.',
        'Do not repeat failed attempts unless new evidence justifies it.',
      ],
      responseFormat: [
        'Current task understanding.',
        'Known failed attempts and do-not-repeat warnings.',
        'Missing evidence.',
        'Next smallest validated step.',
      ],
    },
  }, null, 2)}\n`;
}

function agentInstructionsText() {
  return `# Agent Instructions

## ACE Experience Handoff

This project uses ACE to transfer engineering experience between AI coding sessions, agents, and platforms.

Before changing files:

- Run \`ace experience --json\` and read the objective, recent timeline, failed commands, do-not-repeat notes, and missing evidence.
- If no objective exists, ask the user for the current task or run \`ace start "objective"\` when the task is clear. This starts a new active task boundary without deleting older ledger history.
- Check failed commands before proposing a fix.

During work:

- Run validations through \`ace run "command"\` instead of running important checks directly.
- Record abandoned paths with \`ace note "Do not repeat ..."\`.
- Keep the next step small enough to validate with one command or one focused inspection.

Before handoff:

- Run \`ace brief --compact 8k\` to write \`.ace/handoff.md\`.
- If another agent will continue immediately, include \`ace experience --json\` output or point it to the handoff brief.

Privacy:

- ACE stores command output and notes under \`.ace/\`. Treat this as local task evidence unless the team explicitly decides to commit or share it.
`;
}

function tomlString(value) {
  return JSON.stringify(String(value));
}

function toSlashPath(path) {
  return String(path || '').replace(/\\/g, '/');
}
